# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run smart contract tests in hardhat local env

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node 18. Compiling and unit testing
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run compile
      - run: npm run test
      
    
  analyze:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - run: npm ci --legacy-peer-deps

        - name: Run Slither
          uses: crytic/slither-action@v0.2.0
          with:
            fail-on: none
